/*
 * MainFrame.java, part of the reline project
 * Created on May 14, 2014, 12:02:03 PM
 * Copyright (C) 2014 PSexton
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.psexton.reline;

/**
 *
 * @author PSexton
 */
public class MainFrame extends javax.swing.JFrame {
    private final Model model = new Model();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        // If we've written params to disk previously, reload them
        // Params puts default value for intervalInSeconds to invalid value of -1,
        // so use that to determine if they're previously stored or defaults.
        Params params = Params.readFromPreferences();
        if(params.getIntervalInSeconds() >= 0) {
            interval.getModel().setValue(params.getIntervalInSeconds());
            saveImages.setSelected(params.isWriteImagesToDisk());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intervalLabel = new javax.swing.JLabel();
        interval = new javax.swing.JSpinner();
        saveImages = new javax.swing.JCheckBox();
        runStop = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reline 0.2.1");

        intervalLabel.setText("Interval (seconds):");

        interval.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(15), Integer.valueOf(1), null, Integer.valueOf(1)));

        saveImages.setText("Save images to disk?");

        runStop.setText("Run");
        runStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runStopActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        console.setColumns(20);
        console.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        console.setRows(5);
        console.setEnabled(false);
        jScrollPane1.setViewportView(console);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intervalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interval, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveImages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(runStop, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalLabel)
                    .addComponent(runStop)
                    .addComponent(saveImages))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runStopActionPerformed
        boolean isStarting = runStop.isSelected();

        // Flip component enabling
        interval.setEnabled(!isStarting);
        intervalLabel.setEnabled(!isStarting);
        jScrollPane1.setEnabled(isStarting);
        console.setEnabled(isStarting);
        
        // Either start or stop the app
        if(isStarting) {
            // start
            Params params = new Params(
                    (Integer) interval.getModel().getValue(),
                    saveImages.isSelected());
            params.writeToPreferences();
            model.startMonitor(params, console);
            runStop.setText("Stop");
        }
        else {
            // stop
            model.stopMonitor();
            runStop.setText("Run");
        }
    }//GEN-LAST:event_runStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea console;
    private javax.swing.JSpinner interval;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton runStop;
    private javax.swing.JCheckBox saveImages;
    // End of variables declaration//GEN-END:variables
}
