/*
 * MainFrame.java, part of the reline project
 * Created on May 14, 2014, 12:02:03 PM
 * Copyright (C) 2014 PSexton
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.psexton.reline;

/**
 *
 * @author PSexton
 */
public class MainFrame extends javax.swing.JFrame {
    private final Model model = new Model();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        // If we've written params to disk previously, reload them
        // Params puts default value for intervalInSeconds to invalid value of -1,
        // so use that to determine if they're previously stored or defaults.
        Params params = Params.readFromPreferences();
        if(params.getIntervalInSeconds() >= 0) {
            interval.getModel().setValue(params.getIntervalInSeconds());
            saveImages.setSelected(params.isWriteImagesToDisk());
            restartX.getModel().setValue(params.getRestartX());
            restartY.getModel().setValue(params.getRestartY());
            restartWidth.getModel().setValue(params.getRestartWidth());
            restartHeight.getModel().setValue(params.getRestartHeight());
            joinX.getModel().setValue(params.getJoinX());
            joinY.getModel().setValue(params.getJoinY());
            joinWidth.getModel().setValue(params.getJoinWidth());
            joinHeight.getModel().setValue(params.getJoinHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intervalLabel = new javax.swing.JLabel();
        interval = new javax.swing.JSpinner();
        saveImages = new javax.swing.JCheckBox();
        runStop = new javax.swing.JToggleButton();
        restartLabel = new javax.swing.JLabel();
        restartLabelX = new javax.swing.JLabel();
        restartX = new javax.swing.JSpinner();
        restartLabelY = new javax.swing.JLabel();
        restartY = new javax.swing.JSpinner();
        restartLabelW = new javax.swing.JLabel();
        restartWidth = new javax.swing.JSpinner();
        restartLabelH = new javax.swing.JLabel();
        restartHeight = new javax.swing.JSpinner();
        joinLabel = new javax.swing.JLabel();
        joinLabelX = new javax.swing.JLabel();
        joinX = new javax.swing.JSpinner();
        joinLabelY = new javax.swing.JLabel();
        joinY = new javax.swing.JSpinner();
        joinLabelW = new javax.swing.JLabel();
        joinWidth = new javax.swing.JSpinner();
        joinLabelH = new javax.swing.JLabel();
        joinHeight = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reline 0.3.0");

        intervalLabel.setText("Interval (seconds):");

        interval.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(15), Integer.valueOf(1), null, Integer.valueOf(1)));

        saveImages.setText("Save images to disk?");

        runStop.setText("Run");
        runStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runStopActionPerformed(evt);
            }
        });

        restartLabel.setText("Restart button:");

        restartLabelX.setText("x");

        restartX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(300), Integer.valueOf(0), null, Integer.valueOf(1)));

        restartLabelY.setText("y");

        restartY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(200), Integer.valueOf(0), null, Integer.valueOf(1)));

        restartLabelW.setText("w");

        restartWidth.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(325), Integer.valueOf(1), null, Integer.valueOf(1)));

        restartLabelH.setText("h");

        restartHeight.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(125), Integer.valueOf(1), null, Integer.valueOf(1)));

        joinLabel.setText("Join button:");

        joinLabelX.setText("x");

        joinX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(750), Integer.valueOf(0), null, Integer.valueOf(1)));

        joinLabelY.setText("y");

        joinY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(450), Integer.valueOf(0), null, Integer.valueOf(1)));

        joinLabelW.setText("w");

        joinWidth.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(225), Integer.valueOf(1), null, Integer.valueOf(1)));

        joinLabelH.setText("h");

        joinHeight.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(125), Integer.valueOf(1), null, Integer.valueOf(1)));

        jScrollPane1.setEnabled(false);

        console.setColumns(20);
        console.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        console.setRows(5);
        console.setEnabled(false);
        jScrollPane1.setViewportView(console);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intervalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interval, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveImages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(runStop, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(joinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(restartLabelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartLabelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartLabelW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartLabelH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restartHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(joinLabelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinLabelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinLabelW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinLabelH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalLabel)
                    .addComponent(runStop)
                    .addComponent(saveImages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restartLabel)
                    .addComponent(restartLabelX)
                    .addComponent(restartX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartLabelY)
                    .addComponent(restartY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartLabelW)
                    .addComponent(restartWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartLabelH)
                    .addComponent(restartHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinLabel)
                    .addComponent(joinLabelX)
                    .addComponent(joinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinLabelY)
                    .addComponent(joinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinLabelW)
                    .addComponent(joinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinLabelH)
                    .addComponent(joinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runStopActionPerformed
        boolean isStarting = runStop.isSelected();

        // Flip component enabling
        interval.setEnabled(!isStarting);
        intervalLabel.setEnabled(!isStarting);
        jScrollPane1.setEnabled(isStarting);
        console.setEnabled(isStarting);
        
        // Either start or stop the app
        if(isStarting) {
            // start
            Params params = new Params(
                    (Integer) interval.getModel().getValue(),
                    saveImages.isSelected(),
                    (Integer) restartX.getModel().getValue(),
                    (Integer) restartY.getModel().getValue(),
                    (Integer) restartWidth.getModel().getValue(),
                    (Integer) restartHeight.getModel().getValue(),
                    (Integer) joinX.getModel().getValue(),
                    (Integer) joinY.getModel().getValue(),
                    (Integer) joinWidth.getModel().getValue(),
                    (Integer) joinHeight.getModel().getValue());
            params.writeToPreferences();
            model.startMonitor(params, console);
            runStop.setText("Stop");
        }
        else {
            // stop
            model.stopMonitor();
            runStop.setText("Run");
        }
    }//GEN-LAST:event_runStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea console;
    private javax.swing.JSpinner interval;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner joinHeight;
    private javax.swing.JLabel joinLabel;
    private javax.swing.JLabel joinLabelH;
    private javax.swing.JLabel joinLabelW;
    private javax.swing.JLabel joinLabelX;
    private javax.swing.JLabel joinLabelY;
    private javax.swing.JSpinner joinWidth;
    private javax.swing.JSpinner joinX;
    private javax.swing.JSpinner joinY;
    private javax.swing.JSpinner restartHeight;
    private javax.swing.JLabel restartLabel;
    private javax.swing.JLabel restartLabelH;
    private javax.swing.JLabel restartLabelW;
    private javax.swing.JLabel restartLabelX;
    private javax.swing.JLabel restartLabelY;
    private javax.swing.JSpinner restartWidth;
    private javax.swing.JSpinner restartX;
    private javax.swing.JSpinner restartY;
    private javax.swing.JToggleButton runStop;
    private javax.swing.JCheckBox saveImages;
    // End of variables declaration//GEN-END:variables
}
